# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b03f61895e8da6f8dd21037a474d74f18a6d91b7e1c8b280934c2573e05e0a2a6441469c4dc2ffc98a7bec55cdfe5465564c4b0f5305f0d887de95ff8195f71

test:
  secret_key_base: f37a74101b69d83a80928b1997bbaa8d450a6f4dbe011bfb766e1cf82361265607dcd3432744d9f7ee50837dcb2ccfd0d597155e75bdd8cb0df99a3f172492b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
